# Generated by Django 3.2.4 on 2021-06-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_usersocial_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='occupation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='facebook_link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='github_link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='instagram_link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='linkedin_link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='twitter_link',
            field=models.CharField(max_length=255),
        ),
    ]
