# Generated by Django 3.2.4 on 2021-06-20 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
