# Generated by Django 3.2.4 on 2021-06-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0002_delete_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcomment',
            name='content',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
