# Generated by Django 3.2.4 on 2021-06-27 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0003_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='NewPost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postcomment',
            name='content',
            field=models.TextField(default='NewPostComment'),
            preserve_default=False,
        ),
    ]
