# Generated by Django 3.2.4 on 2021-06-29 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Details', '0003_auto_20210627_2003'),
        ('Details', '0005_auto_20210628_2119'),
    ]

    operations = [
    ]
