# Generated by Django 3.2.4 on 2021-06-12 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sma_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='PasswordResets',
            new_name='PasswordReset',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
        migrations.RenameModel(
            old_name='PostCategories',
            new_name='PostCategory',
        ),
        migrations.RenameModel(
            old_name='PostComments',
            new_name='PostComment',
        ),
        migrations.RenameModel(
            old_name='PostLikes',
            new_name='PostLike',
        ),
        migrations.RenameModel(
            old_name='Socials',
            new_name='Social',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
