# Generated by Django 3.2.4 on 2021-06-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sma_site', '0002_auto_20210612_1952'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social',
            new_name='UserSocial',
        ),
    ]
